//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Driver, Open the application in order to qualify for the 1000 NIS. Werider.
        /// </summary>
        public static string AllDrivers {
            get {
                return ResourceManager.GetString("AllDrivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Passenger, Drivers are waiting to take you to your next destination. Book now!.
        /// </summary>
        public static string AllPassengers {
            get {
                return ResourceManager.GetString("AllPassengers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, Passenger doesn&apos;t accept the ride fee..
        /// </summary>
        public static string AmountDispute {
            get {
                return ResourceManager.GetString("AmountDispute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to business .
        /// </summary>
        public static string Business {
            get {
                return ResourceManager.GetString("Business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Driver, We are sorry to find that your trip has been cancelled..
        /// </summary>
        public static string CanceledTrip1 {
            get {
                return ResourceManager.GetString("CanceledTrip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We hope best of success in the next trip and business venture..
        /// </summary>
        public static string CanceledTrip2 {
            get {
                return ResourceManager.GetString("CanceledTrip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Passenger,  We are sorry to find that your trip has been cancelled..
        /// </summary>
        public static string CanceledTripForPass1 {
            get {
                return ResourceManager.GetString("CanceledTripForPass1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We hope best of success in the next trip and business venture..
        /// </summary>
        public static string CanceledTripForPass2 {
            get {
                return ResourceManager.GetString("CanceledTripForPass2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled Trip.
        /// </summary>
        public static string CanceledTripTitle {
            get {
                return ResourceManager.GetString("CanceledTripTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cash.
        /// </summary>
        public static string Cash {
            get {
                return ResourceManager.GetString("Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to check.
        /// </summary>
        public static string check {
            get {
                return ResourceManager.GetString("check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a Credit Card to charge.
        /// </summary>
        public static string ChooseCreditCard {
            get {
                return ResourceManager.GetString("ChooseCreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Passenger,  Thank you for using Werider App for another trip.  .
        /// </summary>
        public static string CompletedTripPass1 {
            get {
                return ResourceManager.GetString("CompletedTripPass1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We hope you enjoyed the experience..
        /// </summary>
        public static string CompletedTripPass2 {
            get {
                return ResourceManager.GetString("CompletedTripPass2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Driver, You have completed another trip and received {0} NIS..
        /// </summary>
        public static string CompleteTrip1 {
            get {
                return ResourceManager.GetString("CompleteTrip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best of continued success in your business venture..
        /// </summary>
        public static string CompleteTrip2 {
            get {
                return ResourceManager.GetString("CompleteTrip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Trip - Success.
        /// </summary>
        public static string CompleteTripTitle {
            get {
                return ResourceManager.GetString("CompleteTripTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have received a coupon valued at {0} NIS! Enter the code {1} before the next ride to redeem it. *The coupon is valid for one month only. Werider App..
        /// </summary>
        public static string CouponTextForSMS {
            get {
                return ResourceManager.GetString("CouponTextForSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to there is no permission to charge the credit card of the passenger, the payment will be in {0}.the ride is completed.
        /// </summary>
        public static string creaditCardDriverError {
            get {
                return ResourceManager.GetString("creaditCardDriverError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to credit card.
        /// </summary>
        public static string CreditCard {
            get {
                return ResourceManager.GetString("CreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there is no permission to charge your credit card, please pay in cash.
        /// </summary>
        public static string CreditCardPassengerError {
            get {
                return ResourceManager.GetString("CreditCardPassengerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Weride. Your authorization code is {0}.
        /// </summary>
        public static string Driver_Register_SMS_Text {
            get {
                return ResourceManager.GetString("Driver_Register_SMS_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your taxi is here!.
        /// </summary>
        public static string DriverArrived {
            get {
                return ResourceManager.GetString("DriverArrived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your taxi is here!.
        /// </summary>
        public static string DriverArriveInFutureRide {
            get {
                return ResourceManager.GetString("DriverArriveInFutureRide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but the driver canceled the werider at {0} from {1}, Do you want us to look for another driver?.
        /// </summary>
        public static string DriverCancelledFutureRide {
            get {
                return ResourceManager.GetString("DriverCancelledFutureRide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but the driver canceled the werider, Do you want us to look for another driver?.
        /// </summary>
        public static string DriverCancelledRide {
            get {
                return ResourceManager.GetString("DriverCancelledRide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We found driver for you.
        /// </summary>
        public static string DriverFound {
            get {
                return ResourceManager.GetString("DriverFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We found driver for you. his phone is {0}..
        /// </summary>
        public static string DriverFoundSMS {
            get {
                return ResourceManager.GetString("DriverFoundSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but there is no available taxi for you, try again later.
        /// </summary>
        public static string DriverNotFound {
            get {
                return ResourceManager.GetString("DriverNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but there is no available taxi for you, Do you want us to search again?.
        /// </summary>
        public static string driverNotFoundFirst {
            get {
                return ResourceManager.GetString("driverNotFoundFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Werider App.
        /// </summary>
        public static string endMail {
            get {
                return ResourceManager.GetString("endMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A future ride can not be canceled in less than half an hour.
        /// </summary>
        public static string FutureRideCannotCancelled {
            get {
                return ResourceManager.GetString("FutureRideCannotCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Driver! Your version is no longer up-to-date Please update a version in the app store.
        /// </summary>
        public static string massageForDriver {
            get {
                return ResourceManager.GetString("massageForDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear passenger! please update your application.
        /// </summary>
        public static string massageForPassenger {
            get {
                return ResourceManager.GetString("massageForPassenger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have a new ride for you from {0}.
        /// </summary>
        public static string NewRideRequest {
            get {
                return ResourceManager.GetString("NewRideRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Credit Card to charge.
        /// </summary>
        public static string NoCreditCard {
            get {
                return ResourceManager.GetString("NoCreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, we could not find a courier available.   Would you like to find a regular taxi ?.
        /// </summary>
        public static string notFoundTaxiWithCourier {
            get {
                return ResourceManager.GetString("notFoundTaxiWithCourier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, we could not find a taxi available with 30% discount.   Would you like to find a taxi with the regular fare?.
        /// </summary>
        public static string notFoundTaxiWithDiscount {
            get {
                return ResourceManager.GetString("notFoundTaxiWithDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, we could not find a taxi available with handicapped access.   Would you like to find a regular taxi ?.
        /// </summary>
        public static string notFoundTaxiWithHandicapped {
            get {
                return ResourceManager.GetString("notFoundTaxiWithHandicapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The price may not be correct, please enter price again.
        /// </summary>
        public static string PassengerRefuseRidePrice {
            get {
                return ResourceManager.GetString("PassengerRefuseRidePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Ride has ended, please pay the Taxi Driver..
        /// </summary>
        public static string PayInTaxi {
            get {
                return ResourceManager.GetString("PayInTaxi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not charge Credit Card..
        /// </summary>
        public static string PaymentError {
            get {
                return ResourceManager.GetString("PaymentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment successful!.
        /// </summary>
        public static string PaymentSuccessful {
            get {
                return ResourceManager.GetString("PaymentSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your trip was paid by coupon in the amount of {0} NIS.   Werider will be transferring this amount to your account by the end of the month.
        /// </summary>
        public static string PaymentSuccessfulAndCoupon {
            get {
                return ResourceManager.GetString("PaymentSuccessfulAndCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayPal.
        /// </summary>
        public static string Paypal {
            get {
                return ResourceManager.GetString("Paypal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to there is no permission to charge the Paypal account of the passenger, the payment will be in cash.
        /// </summary>
        public static string paypalDriverError {
            get {
                return ResourceManager.GetString("paypalDriverError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there is no permission to charge your Paypal account, please pay in cash.
        /// </summary>
        public static string paypalPassengerError {
            get {
                return ResourceManager.GetString("paypalPassengerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Ride has ended, Payment is made throgh the company.
        /// </summary>
        public static string PayWithBuissness {
            get {
                return ResourceManager.GetString("PayWithBuissness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Ride has ended, Payment is made through your Paypal account.
        /// </summary>
        public static string PayWithPayPal {
            get {
                return ResourceManager.GetString("PayWithPayPal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start the future ride.
        /// </summary>
        public static string recivedFutureRide {
            get {
                return ResourceManager.GetString("recivedFutureRide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area: {0}  Rank:  {1}.
        /// </summary>
        public static string RegionStringForDriver {
            get {
                return ResourceManager.GetString("RegionStringForDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Driver, Welcome to Werider!.
        /// </summary>
        public static string Register1 {
            get {
                return ResourceManager.GetString("Register1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your registration is complete and you are now available to start receiving trips!.
        /// </summary>
        public static string Register2 {
            get {
                return ResourceManager.GetString("Register2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We wish you the best of success in your new business venture..
        /// </summary>
        public static string Register3 {
            get {
                return ResourceManager.GetString("Register3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Complete - Welcome.
        /// </summary>
        public static string RegisterTitle {
            get {
                return ResourceManager.GetString("RegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you remember? you have a ride at {0} from {1}.
        /// </summary>
        public static string ReminderForFutureRide {
            get {
                return ResourceManager.GetString("ReminderForFutureRide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been allocated a ride!.
        /// </summary>
        public static string RideAllocated {
            get {
                return ResourceManager.GetString("RideAllocated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ride ended successfully!.
        /// </summary>
        public static string RideEndedSuccessfull {
            get {
                return ResourceManager.GetString("RideEndedSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ride ended successfully! A tip of {0} was received.
        /// </summary>
        public static string RideEndedSuccessfullAndTip {
            get {
                return ResourceManager.GetString("RideEndedSuccessfullAndTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but the ride already taken by another driver.
        /// </summary>
        public static string RideNotRelevantAnymore {
            get {
                return ResourceManager.GetString("RideNotRelevantAnymore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The price is {0}.
        /// </summary>
        public static string RidePrice {
            get {
                return ResourceManager.GetString("RidePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but your ride was canceled.
        /// </summary>
        public static string riderCancelled {
            get {
                return ResourceManager.GetString("riderCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear driver! please update your application from google play.
        /// </summary>
        public static string sendToGetLocation {
            get {
                return ResourceManager.GetString("sendToGetLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear driver! Your number has been added.   Please register now!  WERIDER DRIVER.
        /// </summary>
        public static string sms_register {
            get {
                return ResourceManager.GetString("sms_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sms.
        /// </summary>
        public static string SMSToPhones {
            get {
                return ResourceManager.GetString("SMSToPhones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but the user cancelled the ride at {0} from {1}.
        /// </summary>
        public static string UserCancelFutureRideRequest {
            get {
                return ResourceManager.GetString("UserCancelFutureRideRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but the user cancelled the ride.
        /// </summary>
        public static string UserCancelRideRequest {
            get {
                return ResourceManager.GetString("UserCancelRideRequest", resourceCulture);
            }
        }
    }
}
