insert into taxistations values(N'כהן אורי','0')
insert into taxistations values(N'1990 בע"מ (כפר סבא 2000 - מירס)','0')
insert into taxistations values(N'איחוד מוניות והסעות הקניונים','0')
insert into taxistations values(N'א.מ 7777 נהריה בע"מ','0')
insert into taxistations values(N'א.ע ארמון בע"מ','0')
insert into taxistations values(N'אביב השמש בע"מ','0')
insert into taxistations values(N'אביבים המושבה','0')
insert into taxistations values(N'אביעוז','0')
insert into taxistations values(N'אביר','0')
insert into taxistations values(N'אבן יהודה','0')
insert into taxistations values(N'אולימפיה (איסק צ''קרשוילי)','0')
insert into taxistations values(N'אור יהודה (כוכב העיר)','0')
insert into taxistations values(N'אחדות','0')
insert into taxistations values(N'אחוזת ראשונים','0')
insert into taxistations values(N'איילה-יונתן אשקלון','0')
insert into taxistations values(N'איכילוב','0')
insert into taxistations values(N'אל-ים','0')
insert into taxistations values(N'אלוזח','0')
insert into taxistations values(N'אלאדל לעד בע"מ','0')
insert into taxistations values(N'ארלוזרוב','0')
insert into taxistations values(N'בון תור','0')
insert into taxistations values(N'בית הכרם','0')
insert into taxistations values(N'בן-גוריון','0')
insert into taxistations values(N'בני ברק','0')
insert into taxistations values(N'בעל הנס','0')
insert into taxistations values(N'בר אילן נביא','0')
insert into taxistations values(N'בת ים אקספרס','0')
insert into taxistations values(N'גבעת שאול','0')
insert into taxistations values(N'גולני','0')
insert into taxistations values(N'גורדון רחובות','0')
insert into taxistations values(N'גורדון רמה בע"מ','0')
insert into taxistations values(N'גוש עציון','0')
insert into taxistations values(N'דקל ישיר ראשל"צ בע"מ','0')
insert into taxistations values(N'דרך צדיקים-אלעד','0')
insert into taxistations values(N'הברון רוטשילד בע"מ','0')
insert into taxistations values(N'הדסה','0')
insert into taxistations values(N'הוד השרון','0')
insert into taxistations values(N'הולילנד','0')
insert into taxistations values(N'הטייסים','0')
insert into taxistations values(N'היכל','0')
insert into taxistations values(N'הכיכר','0')
insert into taxistations values(N'המרינה','0')
insert into taxistations values(N'המשוחרר','0')
insert into taxistations values(N'הנשיא מרום','0')
insert into taxistations values(N'העיר 1990 ראשל"צ (היקב לשעבר) ','0')
insert into taxistations values(N'העיר אשדוד','0')
insert into taxistations values(N'העיר יקנעם','0')
insert into taxistations values(N'העיר מודיעין','0')
insert into taxistations values(N'הפסגה ','0')
insert into taxistations values(N'הצדיקים בני ברק','0')
insert into taxistations values(N'הצומת','0')
insert into taxistations values(N'השבת','0')
insert into taxistations values(N'השרון','0')
insert into taxistations values(N'והסעות','0')
insert into taxistations values(N'ח.ס אטחד','0')
insert into taxistations values(N'חוף הזהב','0')
insert into taxistations values(N'חזי קלאס','0')
insert into taxistations values(N'חנן צ בע"מ','0')
insert into taxistations values(N'טאבה','0')
insert into taxistations values(N'טלסטון','0')
insert into taxistations values(N'טקסי המושבה','0')
insert into taxistations values(N'י.כץ דדו','0')
insert into taxistations values(N'יצהל בית החיל ודקל בע"מ','0')
insert into taxistations values(N'ישראל בע"מ','0')
insert into taxistations values(N'כוכב הדרום','0')
insert into taxistations values(N'כפר סבא','0')
insert into taxistations values(N'לב כרמיאל','0')
insert into taxistations values(N'לב תלפיות','0')
insert into taxistations values(N'מבשרת בע"מ','0')
insert into taxistations values(N'מוניטין פתח תקוה','0')
insert into taxistations values(N'מוניטן 10 ראובן','0')
insert into taxistations values(N'מכז נשרים','0')
insert into taxistations values(N'מלחה','0')
insert into taxistations values(N'מעייני הישועה (שינקין)','0')
insert into taxistations values(N'מעלה אדומים','0')
insert into taxistations values(N'מצדה בע"מ(דוד חי אלון לשעבר)','0')
insert into taxistations values(N'מתי','0')
insert into taxistations values(N'נורדאו','0')
insert into taxistations values(N'נוי-יורק','0')
insert into taxistations values(N'ניצב בע"מ','0')
insert into taxistations values(N'סאקצר איסק','0')
insert into taxistations values(N'סמדר החדשה בע"מ','0')
insert into taxistations values(N'סמדר החדשה בע"מ(טופ גילה)','0')
insert into taxistations values(N'ספורט בע"מ','0')
insert into taxistations values(N'עילית(מודיעין עילית)','0')
insert into taxistations values(N'עצמון','0')
insert into taxistations values(N'ערבה','0')
insert into taxistations values(N'פאן אמריקן','0')
insert into taxistations values(N'פיתוח הרצליה בע"מ','0')
insert into taxistations values(N'פלטין בע"מ','0')
insert into taxistations values(N'צ''יק צ''ק','0')
insert into taxistations values(N'צ''יק צ''ק מרכז','0')
insert into taxistations values(N'צמרת','0')
insert into taxistations values(N'צמרת גילה בע"מ','0')
insert into taxistations values(N'צמרת מעלה אדומים(לירז)','0')
insert into taxistations values(N'קו 51','0')
insert into taxistations values(N'קיראון','0')
insert into taxistations values(N'קניון אשדוד בע"מ','0')
insert into taxistations values(N'קניון בת ים','0')
insert into taxistations values(N'קניון חולון','0')
insert into taxistations values(N'קניון מודיעין','0')
insert into taxistations values(N'קניון סימול','0')
insert into taxistations values(N'קרית ים בע"מ','0')
insert into taxistations values(N'קרלוס','0')
insert into taxistations values(N'שלי עכו','0')
insert into taxistations values(N'רמת גן','0')
insert into taxistations values(N'הכפר','0')
insert into taxistations values(N'השקם','0')
insert into taxistations values(N'גשר','0')
insert into taxistations values(N'רם הקריה','0')
insert into taxistations values(N'הדר לוד','0')
insert into taxistations values(N'אביה','0')
insert into taxistations values(N'צפריר','0')
insert into taxistations values(N'נווה','0')
insert into taxistations values(N'חלוץ עתיד','0')
insert into taxistations values(N'המקדים','0')
insert into taxistations values(N'הפלד','0')
insert into taxistations values(N'המוניטקס','0')
insert into taxistations values(N'עזראלי','0')
insert into taxistations values(N'פתאל','0')
insert into taxistations values(N'חורב','0')
insert into taxistations values(N'שביט','0')
insert into taxistations values(N'נו"ש נשר','0')
insert into taxistations values(N'פתח תקווה','0')
insert into taxistations values(N'הדקה ה99','0')
insert into taxistations values(N'שחמון','0')
insert into taxistations values(N'טקסי כרמל','0')
insert into taxistations values(N'בן גוריון','0')
insert into taxistations values(N'שלי מעלות','0')
insert into taxistations values(N'לימוזין','0')
insert into taxistations values(N'סימול','0')
insert into taxistations values(N'קניון איילון','0')
insert into taxistations values(N'אב ים','0')
insert into taxistations values(N'נרקיס','0')
insert into taxistations values(N'הפלמ"ח','0')
insert into taxistations values(N'שקם מוצקין','0')
insert into taxistations values(N'צבר נתניה','0')
insert into taxistations values(N'שרת החדשה','0')
insert into taxistations values(N'השחר','0')
insert into taxistations values(N'נתניה','0')
insert into taxistations values(N'סמדר צדיקים','0')
insert into taxistations values(N'כיכר דסלר','0')
insert into taxistations values(N'השלום','0')
insert into taxistations values(N'דקר','0')
insert into taxistations values(N'רוממה','0')
insert into taxistations values(N'הדגל','0')
insert into taxistations values(N'אור הקריה','0')
insert into taxistations values(N'הארי','0')
insert into taxistations values(N'קוויה הגליל קטנות','0')
insert into taxistations values(N'קדימה','0')
insert into taxistations values(N'ביאליק מוצקין','0')
insert into taxistations values(N'כלנית כרמיאל','0')
insert into taxistations values(N'המדע','0')
insert into taxistations values(N'הקסטל','0')
insert into taxistations values(N'מעייני הישועה','0')
insert into taxistations values(N'רב שפע(רוממה)','0')
insert into taxistations values(N'רוטשילד','0')
insert into taxistations values(N'רחביה','0')
insert into taxistations values(N'רחובות בע"מ','0')
insert into taxistations values(N'רמות אלון','0')
insert into taxistations values(N'רמז אגודה שיתופית','0')
insert into taxistations values(N'רעננה ניצן','0')
insert into taxistations values(N'שבעת הכוכבים','0')
insert into taxistations values(N'שי-לי','0')
insert into taxistations values(N'שרת','0')
insert into taxistations values(N'תבל','0')
insert into taxistations values(N'תהילה מצדה','0')
insert into taxistations values(N'תל השומר בע"מ','0')
insert into taxistations values(N'תפוח רעננה','0')
insert into taxistations values(N'איחוד בעלי מוניות ראשון','0')

update TaxiStations set EnglishName = HebrewName
