
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Quickode.BallyTaxi.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Account
{

    public Account()
    {

        this.Orders = new HashSet<Order>();

    }


    public long AccountId { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public System.DateTime CreateDate { get; set; }

    public bool Status { get; set; }

    public int BusinessId { get; set; }

    public string UserName { get; set; }

    public Nullable<int> Role { get; set; }



    public virtual Business Business { get; set; }

    public virtual ICollection<Order> Orders { get; set; }

}

}
