
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Quickode.BallyTaxi.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Bank
{

    public Bank()
    {

        this.Drivers = new HashSet<Driver>();

    }


    public int bankId { get; set; }

    public string bankName { get; set; }



    public virtual ICollection<Driver> Drivers { get; set; }

}

}
