
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Quickode.BallyTaxi.Models
{

using System;
    using System.Collections.Generic;
    
public partial class BusinessApprovedPhone
{

    public int BusinessApprovedPhoneId { get; set; }

    public int BusinessId { get; set; }

    public string Phone { get; set; }

    public System.DateTime ApprovedDate { get; set; }

    public Nullable<System.DateTime> CancelledDate { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }



    public virtual Business Business { get; set; }

}

}
