
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Quickode.BallyTaxi.Models
{

using System;
    using System.Collections.Generic;
    
public partial class CarType
{

    public CarType()
    {

        this.Drivers = new HashSet<Driver>();

    }


    public int CarTypeId { get; set; }

    public string HebrewName { get; set; }

    public string EnglishName { get; set; }

    public string StationOperator { get; set; }

    public string IsoCountry { get; set; }

    public string Region { get; set; }



    public virtual ICollection<Driver> Drivers { get; set; }

}

}
