
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Quickode.BallyTaxi.Models
{

using System;
    using System.Collections.Generic;
    
public partial class CountryCode
{

    public string name { get; set; }

    public string name_fr { get; set; }

    public string ISO31661Alpha2 { get; set; }

    public string ISO31661Alpha3 { get; set; }

    public string ISO31661numeric { get; set; }

    public string ITU { get; set; }

    public string MARC { get; set; }

    public string WMO { get; set; }

    public string DS { get; set; }

    public string Dial { get; set; }

    public string FIFA { get; set; }

    public string FIPS { get; set; }

    public string GAUL { get; set; }

    public string IOC { get; set; }

    public string currency_alphabetic_code { get; set; }

    public string currency_country_name { get; set; }

    public string currency_minor_unit { get; set; }

    public string currency_name { get; set; }

    public string currency_numeric_code { get; set; }

    public string is_independent { get; set; }

    public string hebrewName { get; set; }

}

}
