
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Quickode.BallyTaxi.Models
{

using System;
    using System.Collections.Generic;
    
public partial class CreditCard
{

    public CreditCard()
    {

        this.Drivers = new HashSet<Driver>();

    }


    public int CardId { get; set; }

    public long UserId { get; set; }

    public string LastFourDigits { get; set; }

    public int ExpMonth { get; set; }

    public int ExpYear { get; set; }

    public string CVV { get; set; }

    public string CardHolderName { get; set; }

    public string CardHolderId { get; set; }

    public bool IsDefaultCard { get; set; }

    public string Token { get; set; }



    public virtual User User { get; set; }

    public virtual ICollection<Driver> Drivers { get; set; }

}

}
