
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Quickode.BallyTaxi.Models
{

using System;
    using System.Collections.Generic;
    
public partial class CreditCardUser
{

    public int creditCardUser1 { get; set; }

    public Nullable<long> userId { get; set; }

    public string tokenId { get; set; }

    public string cvv { get; set; }

    public string expdate { get; set; }

    public Nullable<bool> isDefault { get; set; }



    public virtual User User { get; set; }

}

}
