//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quickode.BallyTaxi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataLocationDrivers
    {
        public long DataLocationDrivers1 { get; set; }
        public long UserId { get; set; }
        public System.Data.Entity.Spatial.DbGeography Location { get; set; }
        public Nullable<System.DateTime> LastUpdateLocation { get; set; }
        public string Phone { get; set; }
    }
}
