
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Quickode.BallyTaxi.Models
{

    using System;
    using System.Collections.Generic;

    public partial class Driver
    {

        public Driver()
        {

            this.FavoriteDrivers = new HashSet<FavoriteDriver>();

            this.Orders = new HashSet<Order>();

            this.Orders_Drivers = new HashSet<Orders_Drivers>();

            this.DriverRegions = new HashSet<DriverRegion>();

        }


        public long UserId { get; set; }

        public string LicensePlate { get; set; }

        public System.Data.Entity.Spatial.DbGeography Location { get; set; }

        public Nullable<System.DateTime> LastUpdateLocation { get; set; }

        public Nullable<int> CarType { get; set; }

        public string TaxiLicense { get; set; }

        public Nullable<int> PaymentStatus { get; set; }

        public bool WantFutureRide { get; set; }

        public Nullable<int> Status { get; set; }

        public Nullable<int> TaxiStationId { get; set; }

        public Nullable<bool> AcceptsCC { get; set; }

        public Nullable<int> ChargeCCId { get; set; }

        public Nullable<int> BankNumber { get; set; }

        public Nullable<int> BankBranch { get; set; }

        public string BankAccount { get; set; }

        public string BankHolderName { get; set; }

        public string IdentityCardNumber { get; set; }

        public string CCProviderNumber { get; set; }

        public string PayPalId { get; set; }

        public Nullable<int> paymentMethod { get; set; }

        public string driverCode { get; set; }

        public Nullable<int> payment { get; set; }

        public Nullable<int> seats { get; set; }

        public Nullable<int> UpdateLocationStatus { get; set; }

        public Nullable<bool> isHandicapped { get; set; }

        public Nullable<int> courier { get; set; }

        public string companyNumber { get; set; }
        public string tz { get; set; }
        public string studentCard { get; set; }
        public string authorizedDealer { get; set; }

        public Nullable<int> productionYear { get; set; }

        public Nullable<bool> isBlocked { get; set; }

        public Nullable<bool> isPrivate { get; set; }

        public Nullable<System.DateTime> dateEndBlock { get; set; }

        public Nullable<double> heading { get; set; }

        public virtual User User { get; set; }

        public virtual TaxiStation TaxiStation { get; set; }

        public virtual ICollection<FavoriteDriver> FavoriteDrivers { get; set; }

        public virtual ICollection<Order> Orders { get; set; }

        public virtual ICollection<Orders_Drivers> Orders_Drivers { get; set; }

        public virtual CreditCard CreditCard { get; set; }

        public virtual Bank Bank { get; set; }

        public virtual CarType CarType1 { get; set; }

        public virtual ICollection<DriverRegion> DriverRegions { get; set; }

    }

}
