
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Quickode.BallyTaxi.Models
{

using System;
    using System.Collections.Generic;
    
public partial class FavoriteAddress
{

    public long PassengerId { get; set; }

    public System.Data.Entity.Spatial.DbGeography PickUpLocation { get; set; }

    public System.Data.Entity.Spatial.DbGeography DestinationLocation { get; set; }

    public string PickUpAddress { get; set; }

    public string DestinationAddress { get; set; }

    public long FavoriteIndex { get; set; }

    public Nullable<System.DateTime> CreationDate { get; set; }



    public virtual User Passenger { get; set; }

}

}
