
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Quickode.BallyTaxi.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ISR_TaxiStations
{

    public int StationId { get; set; }

    public string StationName { get; set; }

    public string DriverCode { get; set; }



    public virtual TaxiStation TaxiStation { get; set; }

}

}
