
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Quickode.BallyTaxi.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Language
{

    public Language()
    {

        this.Users = new HashSet<User>();

    }


    public int LanguageId { get; set; }

    public string LanguageName { get; set; }

    public string LanguageCulture { get; set; }



    public virtual ICollection<User> Users { get; set; }

}

}
