
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Quickode.BallyTaxi.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Order
{

    public Order()
    {

        this.Orders_Drivers = new HashSet<Orders_Drivers>();

        this.Coupons = new HashSet<Coupon>();

    }


    public long OrderId { get; set; }

    public System.Data.Entity.Spatial.DbGeography PickUpLocation { get; set; }

    public System.Data.Entity.Spatial.DbGeography DestinationLocation { get; set; }

    public string PickUpAddress { get; set; }

    public string DestinationAddress { get; set; }

    public string Notes { get; set; }

    public Nullable<System.DateTime> OrderTime { get; set; }

    public long PassengerId { get; set; }

    public Nullable<long> DriverId { get; set; }

    public int StatusId { get; set; }

    public System.DateTime CreationDate { get; set; }

    public Nullable<int> FlowStep { get; set; }

    public Nullable<System.DateTime> LastUpdateFlowStep { get; set; }

    public Nullable<System.DateTime> EndTime { get; set; }

    public Nullable<int> PaymentMethod { get; set; }

    public Nullable<double> Amount { get; set; }

    public string Currency { get; set; }

    public Nullable<int> Rating { get; set; }

    public Nullable<bool> isInterCity { get; set; }

    public string destinationCityName { get; set; }

    public string pickUpCityName { get; set; }

    public string transactionId { get; set; }

    public string FileNumber { get; set; }

    public Nullable<bool> isFromWeb { get; set; }

    public Nullable<int> tip { get; set; }

    public Nullable<int> businessId { get; set; }

    public Nullable<bool> isWithDiscount { get; set; }

    public Nullable<int> seats { get; set; }

    public Nullable<bool> isHandicapped { get; set; }

    public Nullable<int> courier { get; set; }

    public Nullable<double> priceForInterCity { get; set; }

    public Nullable<long> AccountId { get; set; }

    public Nullable<bool> isReadTheOrder { get; set; }

    public Nullable<bool> isReadTheOrderForDriver { get; set; }

    public Nullable<bool> isVirtual { get; set; }

    public Nullable<int> errorId { get; set; }

    public Nullable<int> orderCount { get; set; }

    public Nullable<bool> isFromStations { get; set; }

    public Nullable<int> PreferedStationId { get; set; }

    public Nullable<bool> isOfflineOrder { get; set; }

    public Nullable<bool> isPayedForDriver { get; set; }

    public string NotesForAdmin { get; set; }

    public Nullable<bool> isInterCityForPayment { get; set; }

    public Nullable<bool> isIVROrder { get; set; }



    public virtual ICollection<Orders_Drivers> Orders_Drivers { get; set; }

    public virtual User Passenger { get; set; }

    public virtual Driver Driver { get; set; }

    public virtual ICollection<Coupon> Coupons { get; set; }

    public virtual Business Business { get; set; }

    public virtual Account Account { get; set; }

    public virtual TaxiStation TaxiStation { get; set; }

}

}
