
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Quickode.BallyTaxi.Models
{

using System;
    using System.Collections.Generic;
    
public partial class PendingUser
{

    public int PendingUserId { get; set; }

    public string CodeValidation { get; set; }

    public string Phone { get; set; }

    public System.DateTime RegistrationDate { get; set; }

    public bool CodeSent { get; set; }

    public System.DateTime CodeExpiration { get; set; }

}

}
