
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Quickode.BallyTaxi.Models
{

using System;
    using System.Collections.Generic;
    
public partial class priceForInterCity_update
{

    public long rowId { get; set; }

    public string pickUpCity { get; set; }

    public string destinationCity { get; set; }

    public Nullable<double> price1 { get; set; }

    public Nullable<double> price2 { get; set; }

}

}
