
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Quickode.BallyTaxi.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Region
{

    public Region()
    {

        this.DriverRegions = new HashSet<DriverRegion>();

        this.LocationForRegions = new HashSet<LocationForRegion>();

    }


    public int regionId { get; set; }

    public string name { get; set; }

    public Nullable<int> taxiStationId { get; set; }



    public virtual ICollection<DriverRegion> DriverRegions { get; set; }

    public virtual TaxiStation TaxiStation { get; set; }

    public virtual ICollection<LocationForRegion> LocationForRegions { get; set; }

}

}
