insert into taxistations values (N'מוניות לב כרמיאל', N'מוניות לב כרמיאל', null, 'IL', null)

  insert into taxistations values (N'מוניות ־ איחוד בעלי מוניות ראשון', N'מוניות ־ איחוד בעלי מוניות ראשון', null, 'IL', null)

insert into taxistations values (N'מוניות ־ כהן אור׳', N'מוניות ־ כהן אור׳', null, 'IL', null)
insert into taxistations values (N'מוניות 1990 בע"מ (כפר סבא 2000 ־ מירס)', N'מוניות 1990 בע"מ (כפר סבא 2000 ־ מירס)', null, 'IL', null)
insert into taxistations values (N'מוניות א.מ 7777 נהריה בע״מ', N'מוניות א.מ 7777 נהריה בע״מ', null, 'IL', null)
insert into taxistations values (N'מוניות א.ע ארמון בע״מ', N'מוניות א.ע ארמון בע״מ', null, 'IL', null)
insert into taxistations values (N'מוניות אביב השמש בע״מ (בעבר שמש הרמה/מבוא)', N'מוניות אביב השמש בע״מ (בעבר שמש הרמה/מבוא)', null, 'IL', null)
insert into taxistations values (N'מוניות אביביה המושבה', N'מוניות אביביה המושבה', null, 'IL', null)
insert into taxistations values (N'מוניות אביעוז', N'מוניות אביעוז', null, 'IL', null)
insert into taxistations values (N'■מוניות אבי-ה', N'■מוניות אבי-ה', null, 'IL', null)
insert into taxistations values (N'מוניות אבן יהודה', N'מוניות אבן יהודה', null, 'IL', null)
insert into taxistations values (N'מוניות אולימפיה (איסק ציקבשוילי)', N'מוניות אולימפיה (איסק ציקבשוילי)', null, 'IL', null)
insert into taxistations values (N'מוניות אור יהודה (כוכב העיר)', N'מוניות אור יהודה (כוכב העיר)', null, 'IL', null)
insert into taxistations values (N'מוניות אחדות', N'מוניות אחדות', null, 'IL', null)
insert into taxistations values (N'מוניות אחוזת ראשונים', N'מוניות אחוזת ראשונים', null, 'IL', null)
insert into taxistations values (N'מוניות א״לה־יונתן אשקלון', N'מוניות א״לה־יונתן אשקלון', null, 'IL', null)
insert into taxistations values (N'מוניות אל-ים', N'מוניות אל-ים', null, 'IL', null)
insert into taxistations values (N'מוניות אלוזח', N'מוניות אלוזח', null, 'IL', null)
insert into taxistations values (N'מוניות אלעד לעד בע״מ', N'מוניות אלעד לעד בע״מ', null, 'IL', null)
insert into taxistations values (N'מוניות ארלוזרוב', N'מוניות ארלוזרוב', null, 'IL', null)
insert into taxistations values (N'מוניות בון תור', N'מוניות בון תור', null, 'IL', null)
insert into taxistations values (N'מוניות בית הכרם', N'מוניות בית הכרם', null, 'IL', null)
insert into taxistations values (N'מוניות בן גוריון', N'מוניות בן גוריון', null, 'IL', null)
insert into taxistations values (N'מוניות בני ברק', N'מוניות בני ברק', null, 'IL', null)
insert into taxistations values (N'מוניות בעל הנס', N'מוניות בעל הנס', null, 'IL', null)
insert into taxistations values (N'מוניות בר אילן נביא', N'מוניות בר אילן נביא', null, 'IL', null)
insert into taxistations values (N'מוניות בת ים אקספרס', N'מוניות בת ים אקספרס', null, 'IL', null)
insert into taxistations values (N'מוניות גבעת שאול', N'מוניות גבעת שאול', null, 'IL', null)
insert into taxistations values (N'מוניות גולני', N'מוניות גולני', null, 'IL', null)
insert into taxistations values (N'מוניות גורדון רחובות', N'מוניות גורדון רחובות', null, 'IL', null)
insert into taxistations values (N'מוניות גורדון רמה בע״מ', N'מוניות גורדון רמה בע״מ', null, 'IL', null)
insert into taxistations values (N'מוניות גוש עציון', N'מוניות גוש עציון', null, 'IL', null)
insert into taxistations values (N'מוניות דקל ישיר ראשל״צ בע״מ', N'מוניות דקל ישיר ראשל״צ בע״מ', null, 'IL', null)
insert into taxistations values (N'מוניות דרך צדיקים־אלעד', N'מוניות דרך צדיקים־אלעד', null, 'IL', null)
insert into taxistations values (N'מוניות הברון רוטשילד בע״מ', N'מוניות הברון רוטשילד בע״מ', null, 'IL', null)
insert into taxistations values (N'מוניות הדסה', N'מוניות הדסה', null, 'IL', null)
insert into taxistations values (N'מוניות הוד השרון', N'מוניות הוד השרון', null, 'IL', null)
insert into taxistations values (N'מוניות הולילנד', N'מוניות הולילנד', null, 'IL', null)
insert into taxistations values (N'מוניות הטייסים', N'מוניות הטייסים', null, 'IL', null)
insert into taxistations values (N'מוניות היכל', N'מוניות היכל', null, 'IL', null)
insert into taxistations values (N'מוניות הכיכר', N'מוניות הכיכר', null, 'IL', null)
insert into taxistations values (N'מוניות המרינה', N'מוניות המרינה', null, 'IL', null)
insert into taxistations values (N'מוניות המשוחרר', N'מוניות המשוחרר', null, 'IL', null)
insert into taxistations values (N'מוניות הנשיא מרום', N'מוניות הנשיא מרום', null, 'IL', null)
insert into taxistations values (N'מוניות העיר 1990 ראשל״צ בע״מ (מוניות היקב לשעבר)', N'מוניות העיר 1990 ראשל״צ בע״מ (מוניות היקב לשעבר)', null, 'IL', null)
insert into taxistations values (N'מוניות העיר אשדוד', N'מוניות העיר אשדוד', null, 'IL', null)
insert into taxistations values (N'מוניות העיר •קנעם', N'מוניות העיר •קנעם', null, 'IL', null)
insert into taxistations values (N'מוניות העיר מודיעין', N'מוניות העיר מודיעין', null, 'IL', null)
insert into taxistations values (N'מוניות הפסגה', N'מוניות הפסגה', null, 'IL', null)
insert into taxistations values (N'מוניות הצדיקים בני ברק', N'מוניות הצדיקים בני ברק', null, 'IL', null)
insert into taxistations values (N'מוניות הצומת', N'מוניות הצומת', null, 'IL', null)
insert into taxistations values (N'מוניות השבת', N'מוניות השבת', null, 'IL', null)
insert into taxistations values (N'מוניות השרון', N'מוניות השרון', null, 'IL', null)
insert into taxistations values (N'מוניות והסעות', N'מוניות והסעות', null, 'IL', null)
insert into taxistations values (N'מוניות ח.0 אטחאד', N'מוניות ח.0 אטחאד', null, 'IL', null)
insert into taxistations values (N'מוניות חוף הזהב', N'מוניות חוף הזהב', null, 'IL', null)
insert into taxistations values (N'מוניות חזי קלאס', N'מוניות חזי קלאס', null, 'IL', null)
insert into taxistations values (N'מ1ניות חנן צ בע״מ', N'מ1ניות חנן צ בע״מ', null, 'IL', null)
insert into taxistations values (N'מוניות טאבה', N'מוניות טאבה', null, 'IL', null)
insert into taxistations values (N'מוניות טלסטון', N'מוניות טלסטון', null, 'IL', null)
insert into taxistations values (N'מוניות טקסי המושבה', N'מוניות טקסי המושבה', null, 'IL', null)
insert into taxistations values (N'מוניות ׳.כץ דדו', N'מוניות ׳.כץ דדו', null, 'IL', null)
insert into taxistations values (N'מוניות ׳צהל בית החיל ודקל בע״מ', N'מוניות ׳צהל בית החיל ודקל בע״מ', null, 'IL', null)
insert into taxistations values (N'מוניות ישראל בע״מ', N'מוניות ישראל בע״מ', null, 'IL', null)
insert into taxistations values (N'מוניות כוכב הדרום', N'מוניות כוכב הדרום', null, 'IL', null)
insert into taxistations values (N'מוניות כפר סבא', N'מוניות כפר סבא', null, 'IL', null)
insert into taxistations values (N'מוניות לב כרמיאל', N'מוניות לב כרמיאל', null, 'IL', null)
insert into taxistations values (N'מוניות לב תלפיות', N'מוניות לב תלפיות', null, 'IL', null)
insert into taxistations values (N'מוניות מבשרת בע״מ', N'מוניות מבשרת בע״מ', null, 'IL', null)
insert into taxistations values (N'מ1ניות מוניטין פתח תקוה', N'מ1ניות מוניטין פתח תקוה', null, 'IL', null)
insert into taxistations values (N'מוניות מוניטן 10 ראובן', N'מוניות מוניטן 10 ראובן', null, 'IL', null)
insert into taxistations values (N'מוניות מכז נשרים', N'מוניות מכז נשרים', null, 'IL', null)
insert into taxistations values (N'מוניות מלחה', N'מוניות מלחה', null, 'IL', null)
insert into taxistations values (N'מוניות מע״ני הישועה (שינקין)', N'מוניות מע״ני הישועה (שינקין)', null, 'IL', null)
insert into taxistations values (N'מוניות מעלה אדומים', N'מוניות מעלה אדומים', null, 'IL', null)
insert into taxistations values (N'מוניות מצדה בע"מ(דוד חי אלון לשעבר)', N'מוניות מצדה בע"מ(דוד חי אלון לשעבר)', null, 'IL', null)
insert into taxistations values (N'מוניות מתי', N'מוניות מתי', null, 'IL', null)
insert into taxistations values (N'מוניות נורדאו', N'מוניות נורדאו', null, 'IL', null)
insert into taxistations values (N'מוניות ניו־יורק', N'מוניות ניו־יורק', null, 'IL', null)
insert into taxistations values (N'מוניות ניצב בע״מ', N'מוניות ניצב בע״מ', null, 'IL', null)
insert into taxistations values (N'מוניות סאקצר איסק', N'מוניות סאקצר איסק', null, 'IL', null)
insert into taxistations values (N'מוניות סמדר החדשה בע״מ', N'מוניות סמדר החדשה בע״מ', null, 'IL', null)
insert into taxistations values (N'מוניות סמדר החדשה בע״מ (טופ גילה)', N'מוניות סמדר החדשה בע״מ (טופ גילה)', null, 'IL', null)
insert into taxistations values (N'מוניות ספורט בע״מ', N'מוניות ספורט בע״מ', null, 'IL', null)
insert into taxistations values (N'מוניות עילית (מודיעין עילית)', N'מוניות עילית (מודיעין עילית)', null, 'IL', null)
insert into taxistations values (N'מוניות עצמון', N'מוניות עצמון', null, 'IL', null)
insert into taxistations values (N'מוניות ערבה', N'מוניות ערבה', null, 'IL', null)
insert into taxistations values (N'מוניות פאן אמריקן', N'מוניות פאן אמריקן', null, 'IL', null)
insert into taxistations values (N'מוניות פיתוח הרצליה בע״מ', N'מוניות פיתוח הרצליה בע״מ', null, 'IL', null)
insert into taxistations values (N'מוניות פלטין בע״מ', N'מוניות פלטין בע״מ', null, 'IL', null)
insert into taxistations values (N'מוניות צייק ציק', N'מוניות צייק ציק', null, 'IL', null)
insert into taxistations values (N'מוניות צייק ציק מרכז', N'מוניות צייק ציק מרכז', null, 'IL', null)
insert into taxistations values (N'מוניות צמרת', N'מוניות צמרת', null, 'IL', null)
insert into taxistations values (N'מוניות צמרת גילה בע״מ', N'מוניות צמרת גילה בע״מ', null, 'IL', null)
insert into taxistations values (N'מוניות צמרת מעלה אדומים(לירז)', N'מוניות צמרת מעלה אדומים(לירז)', null, 'IL', null)
insert into taxistations values (N'מוניות קו 51', N'מוניות קו 51', null, 'IL', null)
insert into taxistations values (N'מוניות ק י רא 11', N'מוניות ק י רא 11', null, 'IL', null)
insert into taxistations values (N'מוניות קניון אשדוד בע״מ', N'מוניות קניון אשדוד בע״מ', null, 'IL', null)
insert into taxistations values (N'מוניות קניון בת ים', N'מוניות קניון בת ים', null, 'IL', null)
insert into taxistations values (N'מוניות קניון חולון', N'מוניות קניון חולון', null, 'IL', null)
insert into taxistations values (N'מוניות קניון מודיעין', N'מוניות קניון מודיעין', null, 'IL', null)
insert into taxistations values (N'-מ 11*1 ת קניון 0ימ1ל', N'-מ 11*1 ת קניון 0ימ1ל', null, 'IL', null)
insert into taxistations values (N'מוניות קרית ים בע״מ', N'מוניות קרית ים בע״מ', null, 'IL', null)
insert into taxistations values (N'Sheli Acco', N'Sheli Acco', null, 'IL', null)
insert into taxistations values (N'Ramat Gan', N'Ramat Gan', null, 'IL', null)
insert into taxistations values (N'Hakefar', N'Hakefar', null, 'IL', null)
insert into taxistations values (N'Hashekem', N'Hashekem', null, 'IL', null)
insert into taxistations values (N'Gesher', N'Gesher', null, 'IL', null)
insert into taxistations values (N'Ram Hakirya', N'Ram Hakirya', null, 'IL', null)
insert into taxistations values (N'Hadar Lod', N'Hadar Lod', null, 'IL', null)
insert into taxistations values (N'Avia', N'Avia', null, 'IL', null)
insert into taxistations values (N'Zafrir', N'Zafrir', null, 'IL', null)
insert into taxistations values (N'Neve', N'Neve', null, 'IL', null)
insert into taxistations values (N'Halutz Atid', N'Halutz Atid', null, 'IL', null)
insert into taxistations values (N'Hamakdim', N'Hamakdim', null, 'IL', null)
insert into taxistations values (N'Hapeled', N'Hapeled', null, 'IL', null)
insert into taxistations values (N'Hamonitax', N'Hamonitax', null, 'IL', null)
insert into taxistations values (N'Azrieli', N'Azrieli', null, 'IL', null)
insert into taxistations values (N'Fatal', N'Fatal', null, 'IL', null)
insert into taxistations values (N'Horev', N'Horev', null, 'IL', null)
insert into taxistations values (N'Shabit', N'Shabit', null, 'IL', null)
insert into taxistations values (N'Neve Sha''anan Nesher', N'Neve Sha''anan Nesher', null, 'IL', null)
insert into taxistations values (N'Petah-Tikva', N'Petah-Tikva', null, 'IL', null)
insert into taxistations values (N'Hadaka Ha-99', N'Hadaka Ha-99', null, 'IL', null)
insert into taxistations values (N'Shachmon', N'Shachmon', null, 'IL', null)
insert into taxistations values (N'Carmel Taxi', N'Carmel Taxi', null, 'IL', null)
insert into taxistations values (N'Ben Gurion', N'Ben Gurion', null, 'IL', null)
insert into taxistations values (N'Sheli Ma''alot', N'Sheli Ma''alot', null, 'IL', null)
insert into taxistations values (N'Limousine', N'Limousine', null, 'IL', null)
insert into taxistations values (N'Simol', N'Simol', null, 'IL', null)
insert into taxistations values (N'Ayalon Mall', N'Ayalon Mall', null, 'IL', null)
insert into taxistations values (N'Av Yam', N'Av Yam', null, 'IL', null)
insert into taxistations values (N'Narkis', N'Narkis', null, 'IL', null)
insert into taxistations values (N'HaPalmach', N'HaPalmach', null, 'IL', null)
insert into taxistations values (N'Shekem Motzkin', N'Shekem Motzkin', null, 'IL', null)
insert into taxistations values (N'Tzabar Netanya', N'Tzabar Netanya', null, 'IL', null)
insert into taxistations values (N'Sharet Hachadasha', N'Sharet Hachadasha', null, 'IL', null)
insert into taxistations values (N'Hashachar', N'Hashachar', null, 'IL', null)
insert into taxistations values (N'Netanya', N'Netanya', null, 'IL', null)
insert into taxistations values (N'Smadar Tzadikim', N'Smadar Tzadikim', null, 'IL', null)
insert into taxistations values (N'Kikar Dessler', N'Kikar Dessler', null, 'IL', null)
insert into taxistations values (N'Hashalom', N'Hashalom', null, 'IL', null)
insert into taxistations values (N'Dakar', N'Dakar', null, 'IL', null)
insert into taxistations values (N'Romema', N'Romema', null, 'IL', null)
insert into taxistations values (N'Hadegel', N'Hadegel', null, 'IL', null)
insert into taxistations values (N'Or Hakirya', N'Or Hakirya', null, 'IL', null)
insert into taxistations values (N'Ha''Ari', N'Ha''Ari', null, 'IL', null)
insert into taxistations values (N'Kavey Hagalil Katanot', N'Kavey Hagalil Katanot', null, 'IL', null)
insert into taxistations values (N'Moniyot Kedima', N'Moniyot Kedima', null, 'IL', null)
insert into taxistations values (N'Bialik Motzkin', N'Bialik Motzkin', null, 'IL', null)
insert into taxistations values (N'Kalanit Karmiel', N'Kalanit Karmiel', null, 'IL', null)
insert into taxistations values (N'Hamada', N'Hamada', null, 'IL', null)
insert into taxistations values (N'Hakastel', N'Hakastel', null, 'IL', null)
insert into taxistations values (N'Me''einei Hayeshua', N'Me''einei Hayeshua', null, 'IL', null)
insert into taxistations values (N'Shimshon', N'Shimshon', null, 'IL', null)
insert into taxistations values (N'Sheli Nahariya', N'Sheli Nahariya', null, 'IL', null)
insert into taxistations values (N'Tiberius', N'Tiberius', null, 'IL', null)
insert into taxistations values (N'קסטל', N'קסטל', null, 'IL', null)
insert into taxistations values (N'שקם', N'שקם', null, 'IL', null)
insert into taxistations values (N'עזריאלי', N'עזריאלי', null, 'IL', null)
insert into taxistations values (N'קווי הגליל(קטנות)', N'קווי הגליל(קטנות)', null, 'IL', null)
insert into taxistations values (N'ר״ג', N'ר״ג', null, 'IL', null)
insert into taxistations values (N'חורב', N'חורב', null, 'IL', null)
insert into taxistations values (N'הדגל', N'הדגל', null, 'IL', null)
insert into taxistations values (N'הדקה ה99', N'הדקה ה99', null, 'IL', null)
insert into taxistations values (N'סימול', N'סימול', null, 'IL', null)
insert into taxistations values (N'שרת החדשה', N'שרת החדשה', null, 'IL', null)
insert into taxistations values (N'נווה', N'נווה', null, 'IL', null)
insert into taxistations values (N'המקדים', N'המקדים', null, 'IL', null)
insert into taxistations values (N'המוניטקס', N'המוניטקס', null, 'IL', null)
insert into taxistations values (N'שביט', N'שביט', null, 'IL', null)
insert into taxistations values (N'הפלד', N'הפלד', null, 'IL', null)
insert into taxistations values (N'ק.איילון', N'ק.איילון', null, 'IL', null)
insert into taxistations values (N'טקסי כרמל', N'טקסי כרמל', null, 'IL', null)
insert into taxistations values (N'הגשר', N'הגשר', null, 'IL', null)
insert into taxistations values (N'שקם מוצקין', N'שקם מוצקין', null, 'IL', null)
insert into taxistations values (N'מעייבי הישועה', N'מעייבי הישועה', null, 'IL', null)
insert into taxistations values (N'אב ים', N'אב ים', null, 'IL', null)
insert into taxistations values (N'לימחיו', N'לימחיו', null, 'IL', null)
insert into taxistations values (N'פ״ת', N'פ״ת', null, 'IL', null)
insert into taxistations values (N'דקר', N'דקר', null, 'IL', null)
insert into taxistations values (N'המדע', N'המדע', null, 'IL', null)
insert into taxistations values (N'סמדר', N'סמדר', null, 'IL', null)
insert into taxistations values (N'השלום', N'השלום', null, 'IL', null)
insert into taxistations values (N'בוגוריון', N'בוגוריון', null, 'IL', null)
insert into taxistations values (N'הפלמ״ח', N'הפלמ״ח', null, 'IL', null)
insert into taxistations values (N'כלנית-כרמיאל', N'כלנית-כרמיאל', null, 'IL', null)
insert into taxistations values (N'נו״ש נשר', N'נו״ש נשר', null, 'IL', null)
insert into taxistations values (N'קדימה', N'קדימה', null, 'IL', null)
insert into taxistations values (N'רוממה', N'רוממה', null, 'IL', null)
insert into taxistations values (N'אביה', N'אביה', null, 'IL', null)
insert into taxistations values (N'ביאליק מוצקיו', N'ביאליק מוצקיו', null, 'IL', null)
insert into taxistations values (N'החלתי', N'החלתי', null, 'IL', null)
insert into taxistations values (N'ככרדסלר', N'ככרדסלר', null, 'IL', null)
insert into taxistations values (N'רם הקריה', N'רם הקריה', null, 'IL', null)
insert into taxistations values (N'צפריר', N'צפריר', null, 'IL', null)
insert into taxistations values (N'הכפר־ פרדסיה', N'הכפר־ פרדסיה', null, 'IL', null)
insert into taxistations values (N'אור הקריה', N'אור הקריה', null, 'IL', null)
insert into taxistations values (N'הדר לוד', N'הדר לוד', null, 'IL', null)
insert into taxistations values (N'נרקיס', N'נרקיס', null, 'IL', null)
insert into taxistations values (N'שמשוו', N'שמשוו', null, 'IL', null)
insert into taxistations values (N'צבר', N'צבר', null, 'IL', null)
insert into taxistations values (N'השחר', N'השחר', null, 'IL', null)
insert into taxistations values (N'נתניה', N'נתניה', null, 'IL', null)
insert into taxistations values (N'פחאל', N'פחאל', null, 'IL', null)
insert into taxistations values (N'שהמוו', N'שהמוו', null, 'IL', null)
insert into taxistations values (N'שלי עכו', N'שלי עכו', null, 'IL', null)
insert into taxistations values (N'הארי', N'הארי', null, 'IL', null)
insert into taxistations values (N'ח1', N'ח1', null, 'IL', null)
insert into taxistations values (N'שלי מעלות', N'שלי מעלות', null, 'IL', null)

